#!/usr/bin/python3

import sys

from chart import Stack, Chart, Candle, print_buy, print_sell


class Bot:
    def __init__(self, pair: str):
        self.botState = BotState()
        self.stacks = []
        self.pair = pair
        self.pause = 0

    def run(self):
        while True:
            reading = input()
            if len(reading) == 0:
                continue
            self.parse(reading)

    def parse(self, info: str):
        tmp = info.split(" ")
        if tmp[0] == "settings":
            self.botState.update_settings(tmp[1], tmp[2])
        if tmp[0] == "update":
            if tmp[1] == "game":
                self.botState.update_game(tmp[2], tmp[3])
                for stack in self.stacks:
                    stack.update(self.botState.charts[self.pair].closes[-1])
        if tmp[0] == "action":
            self.execute_action()

    def execute_action(self):
        close = self.botState.charts[self.pair].closes[-1]
        high = self.botState.charts[self.pair].highs[-1]
        low = self.botState.charts[self.pair].lows[-1]
        self.pause = self.pause - 1 if self.pause > 0 else 0 
        if not self.check_stacks_bounds(close):
            dollars = self.botState.stacks["USDT"]
            affordable = dollars / close
            if dollars > 1:
                upper = self.botState.charts[self.pair].indicators["bollinger2_20_upper"][-1]
                lower = self.botState.charts[self.pair].indicators["bollinger2_20_lower"][-1]
                buy_signal = lower > min(low, close)
                sell_signal = upper < max(high, close)
                ema20 = self.botState.charts[self.pair].indicators["ema20"][-1]
                ema50 = self.botState.charts[self.pair].indicators["ema50"][-1]
                tendency = ema20 > ema50
                if self.pause == 0 and buy_signal and tendency:
                    stop_loss = close * 0.95
                    take_profit = close * 1.10
                    self.buy(affordable, close, stop_loss, take_profit, trailing_stop=0.01)
                    self.pause = 2
                elif sell_signal and self.get_sum_of_stacks() > 0:
                    self.sell()
                    self.pause = 2
                else:
                    self.do_nothing()
                
            else:
                self.do_nothing()
        else:
            self.pause = 2

    def buy(self, amount: float, closing_price : float, stop_loss: float, take_profit: float, trailing_stop: float = None):
        self.stacks.append(
            Stack(
                amount, closing_price, stop_loss, take_profit, self.pair, self.botState.transactionFee, trailing_stop
            )
        )

    def sell(self, amount: float = None):
        sum = 0
        if amount is None:
            amount = self.get_sum_of_stacks()
        if amount > self.get_sum_of_stacks():
            raise Exception("You are trying to sell more than you have")
        if amount < 0:
            raise Exception("You are trying to sell a negative amount")
        if amount == 0:
            raise Exception("You are trying to sell 0")
        while sum < amount:
            stack = self.stacks.pop(0)
            sum += stack.amount
        print_sell(self.pair, amount)

    def get_sum_of_stacks(self):
        sum = 0
        for stack in self.stacks:
            sum += stack.amount
        return sum

    def check_stacks_bounds(self, closing_price: float):
        sum = 0
        for stack in self.stacks:
            if stack.is_out_of_bounds(closing_price):
                sum += stack.amount
                self.stacks.remove(stack)
        if sum > 0:
            print_sell(self.pair, sum)
            print(sum, "sold because of TP or SL", file=sys.stderr, flush=True)
            return True
        return False

    def do_nothing(self):
        print("no_moves", flush=True)


class BotState:
    def __init__(self):
        self.timeBank = 0
        self.maxTimeBank = 0
        self.timePerMove = 1
        self.candleInterval = 1
        self.candleFormat = []
        self.candlesTotal = 0
        self.candlesGiven = 0
        self.initialStack = 0
        self.transactionFee = 0.1
        self.date = 0
        self.stacks = dict()
        self.charts = dict()

    def update_chart(self, pair: str, new_candle_str: str):
        if not (pair in self.charts):
            self.charts[pair] = Chart()
        new_candle_obj = Candle(self.candleFormat, new_candle_str)
        self.charts[pair].add_candle(new_candle_obj)

    def update_stack(self, key: str, value: float):
        self.stacks[key] = value

    def update_settings(self, key: str, value: str):
        if key == "timebank":
            self.maxTimeBank = int(value)
            self.timeBank = int(value)
        if key == "time_per_move":
            self.timePerMove = int(value)
        if key == "candle_interval":
            self.candleInterval = int(value)
        if key == "candle_format":
            self.candleFormat = value.split(",")
        if key == "candles_total":
            self.candlesTotal = int(value)
        if key == "candles_given":
            self.candlesGiven = int(value)
        if key == "initial_stack":
            self.initialStack = int(value)
        if key == "transaction_fee_percent":
            self.transactionFee = float(value)

    def update_game(self, key: str, value: str):
        if key == "next_candles":
            new_candles = value.split(";")
            self.date = int(new_candles[0].split(",")[1])
            for candle_str in new_candles:
                candle_infos = candle_str.strip().split(",")
                self.update_chart(candle_infos[0], candle_str)
        if key == "stacks":
            new_stacks = value.split(",")
            for stack_str in new_stacks:
                stack_infos = stack_str.strip().split(":")
                self.update_stack(stack_infos[0], float(stack_infos[1]))


if __name__ == "__main__":
    try:
        mybot = Bot("USDT_BTC")
        mybot.run()
    except Exception as e:
        print(e, file=sys.stderr)
        sys.exit(84)
